import assert from 'node:assert/strict';
import { fork } from 'node:child_process';
import { randomBytes, randomUUID } from 'node:crypto';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { claimBootstrap, changeRole, commitCatalog, connectTestDatabase, prepareTestSchema, transaction } from '../../scripts/admin-poc/store.mjs';

const url = process.env.OAKTECH_POC_DATABASE_URL;
const snapshot = (value = 'fixture') => ({ schemaVersion: 1, products: [{ slug: value }], releases: [] });

async function fixture(t, count = 4) {
  const client = await connectTestDatabase(url);
  const schema = `oaktech_poc_${randomUUID().replaceAll('-', '')}`;
  const installationId = randomUUID();
  const token = randomBytes(32).toString('hex');
  const children = [];
  const actors = Array.from({ length: count }, () => randomUUID());
  await prepareTestSchema(client, schema, installationId, token, actors);
  await client.query(`SET search_path TO "${schema}", pg_catalog`);
  t.after(async () => {
    for (const child of children) {
      if (child.exitCode === null && child.signalCode === null) { const done = new Promise((resolve) => child.once('exit', resolve)); child.kill('SIGKILL'); await done; }
    }
    // Schema name was generated by this test, never copied from connection input.
    await client.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
    await client.end();
  });
  return { client, schema, installationId, token, actors, children };
}

function worker(t, fixture, operation, extraEnv = {}) {
  const child = fork(new URL('../../scripts/admin-poc/worker.mjs', import.meta.url), [], {
    env: { ...process.env, OAKTECH_POC_DATABASE_URL: url, ...extraEnv },
    stdio: ['ignore', 'ignore', 'pipe', 'ipc'],
  });
  fixture.children.push(child);
  const events = [];
  const pending = [];
  let exited = false;
  const resolveEvent = (value) => {
    events.push(value);
    for (const listener of [...pending]) {
      if (listener.kind === value.kind) { clearTimeout(listener.timer); pending.splice(pending.indexOf(listener), 1); listener.resolve(value); }
    }
  };
  child.on('message', resolveEvent);
  child.on('exit', () => {
    exited = true;
    for (const listener of pending.splice(0)) { clearTimeout(listener.timer); listener.reject(new Error(`POC_WORKER_EXIT_BEFORE_${listener.kind}`)); }
  });
  child.on('error', () => resolveEvent({ kind: 'result', ok: false, code: 'POC_WORKER_START_FAILED' }));
  child.stderr.resume();
  t.after(async () => {
    if (!exited) { const done = new Promise((resolve) => child.once('exit', resolve)); child.kill('SIGKILL'); await done; }
  });
  child.send({ schema: fixture.schema, installationId: fixture.installationId, ...operation });
  const waitFor = (kind) => {
    const event = events.find((event) => event.kind === kind);
    if (event) return Promise.resolve(event);
    if (exited) return Promise.reject(new Error(`POC_WORKER_ALREADY_EXITED_${kind}`));
    return new Promise((resolve, reject) => {
      const listener = { kind, resolve, reject };
      listener.timer = setTimeout(() => { pending.splice(pending.indexOf(listener), 1); reject(new Error(`POC_WORKER_TIMEOUT_${kind}`)); }, 15000);
      pending.push(listener);
    });
  };
  return { child, waitFor, resume: (kind) => child.send({ continue: kind }), events };
}
async function start(w) { await w.waitFor('ready'); w.resume('ready'); }
async function initialized(t) {
  const f = await fixture(t);
  await claimBootstrap(f.client, f.schema, f.installationId, f.actors[0], f.token);
  return f;
}
async function terminateBackend(f, pid) {
  const { rows } = await f.client.query('SELECT pg_terminate_backend($1) AS terminated', [pid]);
  assert.equal(rows[0].terminated, true);
  // Wait until the backend is gone rather than depending on an arbitrary sleep.
  for (let i = 0; i < 50; i++) {
    const result = await f.client.query('SELECT 1 FROM pg_stat_activity WHERE pid=$1', [pid]);
    if (!result.rowCount) return;
    await new Promise((resolve) => setTimeout(resolve, 20));
  }
  throw new Error('POC_BACKEND_DID_NOT_TERMINATE');
}

test('PG-01: 20 independent processes compete; exactly one bootstrap commits', { timeout: 30000 }, async (t) => {
  const f = await fixture(t, 20);
  const workers = f.actors.map((actor) => worker(t, f, { action: 'bootstrap', actor, token: f.token }));
  const connected = await Promise.all(workers.map((w) => w.waitFor('connected')));
  assert.equal(new Set(connected.map((c) => c.nodePid)).size, 20);
  assert.equal(new Set(connected.map((c) => c.backendPid)).size, 20);
  await Promise.all(workers.map(start));
  const results = await Promise.all(workers.map((w) => w.waitFor('result')));
  assert.equal(results.filter((r) => r.ok).length, 1);
  assert.ok(results.filter((r) => !r.ok).every((r) => r.code === 'POC_ALREADY_INITIALIZED'));
  assert.equal((await f.client.query("SELECT * FROM principal WHERE role='super_admin'")).rowCount, 1);
  assert.equal((await f.client.query("SELECT * FROM audit WHERE action='bootstrap'")).rowCount, 1);
  const state = (await f.client.query('SELECT * FROM installation')).rows[0];
  assert.ok(state.initialized_at && state.consumed_at);
});

test('PG-02: failure after role update rolls back role, token, marker and audit', async (t) => {
  const f = await fixture(t);
  await assert.rejects(() => claimBootstrap(f.client, f.schema, f.installationId, f.actors[0], f.token, {
    afterRole: () => { throw new Error('POC_INJECTED_FAILURE'); },
  }), /POC_INJECTED_FAILURE/);
  assert.equal((await f.client.query("SELECT * FROM principal WHERE role<>'user'")).rowCount, 0);
  assert.equal((await f.client.query('SELECT * FROM audit')).rowCount, 0);
  assert.equal((await f.client.query('SELECT initialized_at FROM installation')).rows[0].initialized_at, null);
  await claimBootstrap(f.client, f.schema, f.installationId, f.actors[0], f.token);
});

test('PG-03: process death mid-bootstrap rolls back and releases the row lock', async (t) => {
  const f = await fixture(t);
  const w = worker(t, f, { action: 'bootstrap', actor: f.actors[0], token: f.token, pauseAfterRole: true });
  await start(w); await w.waitFor('afterRole');
  const exit = new Promise((resolve) => w.child.once('exit', resolve));
  w.child.kill('SIGKILL'); await exit;
  await claimBootstrap(f.client, f.schema, f.installationId, f.actors[1], f.token);
  const rows = (await f.client.query("SELECT id FROM principal WHERE role='super_admin'")).rows;
  assert.deepEqual(rows.map((r) => r.id), [f.actors[1]]);
  assert.equal((await f.client.query('SELECT * FROM audit')).rowCount, 1);
});

test('PG-04: wrong/expired token and wrong installation do not grant anything', async (t) => {
  const f = await fixture(t);
  await assert.rejects(() => claimBootstrap(f.client, f.schema, f.installationId, f.actors[0], 'wrong'), /POC_INVALID_BOOTSTRAP/);
  await assert.rejects(() => claimBootstrap(f.client, f.schema, randomUUID(), f.actors[0], f.token), /POC_INSTALLATION_MISMATCH/);
  await f.client.query("UPDATE installation SET expires_at=clock_timestamp()-interval '1 second'");
  await assert.rejects(() => claimBootstrap(f.client, f.schema, f.installationId, f.actors[0], f.token), /POC_INVALID_BOOTSTRAP/);
  assert.equal((await f.client.query("SELECT * FROM principal WHERE role<>'user'")).rowCount, 0);
  assert.equal((await f.client.query('SELECT * FROM audit')).rowCount, 0);
});

test('PG-05: initialized installation stays closed even with no effective superadmin', async (t) => {
  const f = await initialized(t);
  // Simulates an external admin/restore fault, not a supported role mutation.
  await f.client.query("UPDATE principal SET status='disabled' WHERE role='super_admin'");
  const fresh = await connectTestDatabase(url);
  try { await assert.rejects(() => claimBootstrap(fresh, f.schema, f.installationId, f.actors[1], f.token), /POC_ALREADY_INITIALIZED/); }
  finally { await fresh.end(); }
  assert.equal((await f.client.query("SELECT * FROM principal WHERE role='super_admin'")).rowCount, 1);
});

test('PG-06: exact issuer/subject identity and database role constraints', async (t) => {
  const f = await fixture(t);
  await f.client.query('INSERT INTO principal(id,provider,issuer,subject) VALUES ($1,$2,$3,$4)', [randomUUID(), 'test-oidc', 'https://other.example.invalid', 'fixture-0']);
  await f.client.query('INSERT INTO principal(id,provider,issuer,subject) VALUES ($1,$2,$3,$4)', [randomUUID(), 'test-oidc', 'https://identity.example.invalid', 'Fixture-0']);
  await assert.rejects(() => f.client.query('INSERT INTO principal(id,provider,issuer,subject) VALUES ($1,$2,$3,$4)', [randomUUID(), 'test-oidc', 'https://identity.example.invalid', 'fixture-0']), { code: '23505' });
  await assert.rejects(() => f.client.query("UPDATE principal SET role='root' WHERE id=$1", [f.actors[0]]), { code: '23514' });
});

test('PG-07: ordinary users/admins cannot change roles; last superadmin cannot step down', async (t) => {
  const f = await initialized(t);
  await assert.rejects(() => changeRole(f.client, f.schema, f.installationId, f.actors[1], f.actors[1], 'super_admin', 0), /POC_FORBIDDEN/);
  await changeRole(f.client, f.schema, f.installationId, f.actors[0], f.actors[1], 'admin', 0);
  await assert.rejects(() => changeRole(f.client, f.schema, f.installationId, f.actors[1], f.actors[2], 'admin', 0), /POC_FORBIDDEN/);
  await assert.rejects(() => changeRole(f.client, f.schema, f.installationId, f.actors[0], f.actors[0], 'user', 1), /POC_LAST_SUPER_ADMIN/);
});

test('PG-08: concurrent self-demotions cannot remove both superadmins', async (t) => {
  const f = await initialized(t);
  await changeRole(f.client, f.schema, f.installationId, f.actors[0], f.actors[1], 'super_admin', 0);
  const workers = [0, 1].map((index) => worker(t, f, { action: 'role', actor: f.actors[index], target: f.actors[index], role: 'user', expectedRevision: 1 }));
  await Promise.all(workers.map(start));
  const results = await Promise.all(workers.map((w) => w.waitFor('result')));
  assert.equal(results.filter((r) => r.ok).length, 1);
  assert.equal(results.find((r) => !r.ok).code, 'POC_LAST_SUPER_ADMIN');
  assert.equal((await f.client.query("SELECT * FROM principal WHERE role='super_admin' AND status='active'")).rowCount, 1);
});

test('PG-09: catalog intent, canonical snapshot and audit are one transaction', async (t) => {
  const f = await initialized(t);
  await assert.rejects(() => commitCatalog(f.client, f.schema, f.installationId, f.actors[0], randomUUID(), 0, snapshot(), {
    afterCatalog: () => { throw new Error('POC_INJECTED_FAILURE'); },
  }), /POC_INJECTED_FAILURE/);
  assert.equal((await f.client.query('SELECT revision FROM catalog')).rows[0].revision, 0);
  assert.equal((await f.client.query('SELECT * FROM committed_command')).rowCount, 0);
  assert.equal((await f.client.query("SELECT * FROM audit WHERE action='catalog.commit'")).rowCount, 0);
});

test('PG-10: request retries do not duplicate writes; reused IDs and stale revisions reject', async (t) => {
  const f = await initialized(t); const id = randomUUID();
  assert.deepEqual(await commitCatalog(f.client, f.schema, f.installationId, f.actors[0], id, 0, snapshot()), { revision: 1, replay: false });
  assert.deepEqual(await commitCatalog(f.client, f.schema, f.installationId, f.actors[0], id, 0, snapshot()), { revision: 1, replay: true });
  await assert.rejects(() => commitCatalog(f.client, f.schema, f.installationId, f.actors[0], id, 1, snapshot('different')), /POC_IDEMPOTENCY_CONFLICT/);
  await assert.rejects(() => commitCatalog(f.client, f.schema, f.installationId, f.actors[0], randomUUID(), 0, snapshot()), /POC_CATALOG_CONFLICT/);
  assert.equal((await f.client.query('SELECT * FROM committed_command')).rowCount, 1);
});

test('PG-11: revoked admin is denied at the next independent process write', async (t) => {
  const f = await initialized(t);
  await changeRole(f.client, f.schema, f.installationId, f.actors[0], f.actors[1], 'admin', 0);
  await changeRole(f.client, f.schema, f.installationId, f.actors[0], f.actors[1], 'user', 1);
  const w = worker(t, f, { action: 'catalog', actor: f.actors[1], requestId: randomUUID(), expectedRevision: 0, snapshot: snapshot() });
  await start(w); assert.equal((await w.waitFor('result')).code, 'POC_FORBIDDEN');
  assert.equal((await f.client.query('SELECT revision FROM catalog')).rows[0].revision, 0);
});

test('PG-12: in-flight SQL commit linearizes before revocation; later writes deny', async (t) => {
  const f = await initialized(t);
  await changeRole(f.client, f.schema, f.installationId, f.actors[0], f.actors[1], 'admin', 0);
  const edit = worker(t, f, { action: 'catalog', actor: f.actors[1], requestId: randomUUID(), expectedRevision: 0, snapshot: snapshot(), pauseAfterAuthorization: true });
  await start(edit); await edit.waitFor('afterAuthorization');
  const revoke = worker(t, f, { action: 'role', actor: f.actors[0], target: f.actors[1], role: 'user', expectedRevision: 1 });
  await start(revoke);
  const revokePid = (await revoke.waitFor('connected')).backendPid;
  let observedLock = false;
  for (let i = 0; i < 100; i++) {
    const result = await f.client.query("SELECT wait_event_type FROM pg_stat_activity WHERE pid=$1", [revokePid]);
    if (result.rows[0]?.wait_event_type === 'Lock') { observedLock = true; break; }
    await new Promise((resolve) => setTimeout(resolve, 10));
  }
  assert.ok(observedLock, 'revocation actually waits on the database, not a JavaScript mock');
  edit.resume('afterAuthorization');
  assert.equal((await edit.waitFor('result')).ok, true);
  assert.equal((await revoke.waitFor('result')).ok, true);
  await assert.rejects(() => commitCatalog(f.client, f.schema, f.installationId, f.actors[1], randomUUID(), 1, snapshot('later')), /POC_FORBIDDEN/);
});

test('PG-13: terminated SQL connection cannot commit a checked-but-uncommitted catalog', async (t) => {
  const f = await initialized(t);
  await changeRole(f.client, f.schema, f.installationId, f.actors[0], f.actors[1], 'admin', 0);
  const w = worker(t, f, { action: 'catalog', actor: f.actors[1], requestId: randomUUID(), expectedRevision: 0, snapshot: snapshot(), pauseAfterAuthorization: true });
  await start(w); await w.waitFor('afterAuthorization');
  await terminateBackend(f, (await w.waitFor('connected')).backendPid);
  await changeRole(f.client, f.schema, f.installationId, f.actors[0], f.actors[1], 'user', 1);
  w.resume('afterAuthorization');
  assert.equal((await w.waitFor('result')).ok, false);
  assert.equal((await f.client.query('SELECT revision FROM catalog')).rows[0].revision, 0);
  assert.equal((await f.client.query('SELECT * FROM committed_command')).rowCount, 0);
});

test('PG-14 COUNTEREXAMPLE: SQL lock plus filesystem rename alone is unsafe after disconnection', async (t) => {
  const f = await initialized(t);
  await changeRole(f.client, f.schema, f.installationId, f.actors[0], f.actors[1], 'admin', 0);
  const directory = await mkdtemp(path.join(os.tmpdir(), 'oaktech-poc-counterexample-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  await writeFile(path.join(directory, 'catalog.json'), JSON.stringify(snapshot('before')));
  const w = worker(t, f, { action: 'unsafe-json-demonstration', actor: f.actors[1], snapshot: snapshot('unauthorized-late-write') }, { OAKTECH_POC_UNSAFE_OUTPUT: directory });
  await start(w); await w.waitFor('afterAuthorization');
  await terminateBackend(f, (await w.waitFor('connected')).backendPid);
  await changeRole(f.client, f.schema, f.installationId, f.actors[0], f.actors[1], 'user', 1);
  w.resume('afterAuthorization'); await w.waitFor('unsafeFileWritten');
  assert.equal((await w.waitFor('result')).ok, false, 'SQL reports failure');
  assert.equal(JSON.parse(await readFile(path.join(directory, 'catalog.json'), 'utf8')).products[0].slug, 'unauthorized-late-write', 'filesystem changed after acknowledged revocation despite SQL rollback');
});

test('PG-15: missing installation/schema fails closed and never auto-provisions', async (t) => {
  const f = await fixture(t);
  await f.client.query('DELETE FROM installation');
  await assert.rejects(() => claimBootstrap(f.client, f.schema, f.installationId, f.actors[0], f.token), /POC_INSTALLATION_MISMATCH/);
  await assert.rejects(() => transaction(f.client, `oaktech_poc_${randomUUID().replaceAll('-', '')}`, () => f.client.query('SELECT * FROM installation')), { code: '42P01' });
  assert.equal((await f.client.query('SELECT * FROM installation')).rowCount, 0);
});

test('PG-17: bootstrap expiry is rechecked after waiting for the installation lock', async (t) => {
  const f = await fixture(t);
  const w = worker(t, f, { action: 'bootstrap', actor: f.actors[0], token: f.token });
  await w.waitFor('ready');
  const pid = (await w.waitFor('connected')).backendPid;
  await f.client.query("UPDATE installation SET expires_at=clock_timestamp()+interval '800 milliseconds'");
  await f.client.query('BEGIN');
  try {
    await f.client.query('SELECT * FROM installation WHERE singleton FOR UPDATE');
    w.resume('ready');
    let blocked = false;
    for (let i = 0; i < 100; i++) {
      await f.client.query('SELECT pg_stat_clear_snapshot()');
      const row = (await f.client.query('SELECT wait_event_type FROM pg_stat_activity WHERE pid=$1', [pid])).rows[0];
      if (row?.wait_event_type === 'Lock') { blocked = true; break; }
      await new Promise((resolve) => setTimeout(resolve, 10));
    }
    assert.ok(blocked);
    await f.client.query('SELECT pg_sleep(1.0)');
    await f.client.query('COMMIT');
  } finally { await f.client.query('ROLLBACK'); }
  const result = await w.waitFor('result');
  assert.equal(result.ok, false);
  assert.equal(result.code, 'POC_INVALID_BOOTSTRAP');
});
