import { ProductTier } from "@/types/subscriptions";

export const SUBSCRIPTION_TIERS: ProductTier[] = [
  {
    name: "Beta",
    id: "tier-beta",
    productId: "prod_14viZfNnyQTgVW94fXte47",
    priceMonthly: "$0",
    description: "Free MVP for validating the extension workflow.",
    features: [
      "Extract visible profile tweets",
      "Up to 10,000 tweets per run",
      "JSON, CSV, TXT, HTML, and Markdown exports",
      "Local browser processing",
      "Chrome developer-mode loading",
    ],
    featured: true,
    discountCode: "",
  },
  {
    name: "Pro",
    id: "tier-pro",
    productId: "prod_14viZfNnyQTgVW94fXte47",
    priceMonthly: "TBD",
    description: "Planned commercial license for advanced export workflows.",
    features: [
      "Everything in Beta",
      "Advanced media resource export",
      "License activation",
      "Priority support",
      "Early access to new features",
    ],
    featured: false,
    discountCode: "",
  },
  {
    name: "Team",
    id: "tier-team",
    productId: "prod_14viZfNnyQTgVW94fXte47",
    priceMonthly: "TBD",
    description: "Planned license for research and content teams.",
    features: [
      "Everything in Pro",
      "Multiple seats",
      "Team onboarding",
      "Centralized license management",
      "Commercial support",
    ],
    featured: false,
    discountCode: "",
  },
];

export const CREDITS_TIERS: ProductTier[] = [
  {
    name: "Beta Access",
    id: "product-beta-access",
    productId: "prod_14viZfNnyQTgVW94fXte47",
    priceMonthly: "$0",
    description: "Test the current X Tweet Extractor MVP.",
    features: [
      "Developer-mode Chrome install",
      "Visible tweet extraction",
      "Local text exports",
      "Feedback welcome",
    ],
    featured: true,
    discountCode: "",
  },
  {
    name: "Pro Waitlist",
    id: "product-pro-waitlist",
    productId: "prod_14viZfNnyQTgVW94fXte47",
    priceMonthly: "TBD",
    description: "Follow upcoming commercial features.",
    features: [
      "Advanced export roadmap",
      "License activation planned",
      "Priority feature updates",
      "Early tester access",
    ],
    featured: false,
    discountCode: "",
  },
  {
    name: "Support",
    id: "product-support",
    productId: "prod_14viZfNnyQTgVW94fXte47",
    priceMonthly: "Email",
    description: "Ask questions or report extraction issues.",
    features: [
      "Support by email",
      "Bug reports",
      "Publishing questions",
      "Feature requests",
    ],
    featured: false,
    discountCode: "",
  },
];
